### ISSUE TITLE
Other pages

### ISSUE THREAD

**Issue by duchao1990** [wataruoguchi/Ionic-Tabbed-Slidebox-Scroll-Extension#1]
I want to write <ion-view> </ion-view>  to other HTML pages.How to load this page

**Comment by wataruoguchi** [comment]
Hi @duchao1990 ,
Sorry, I don't get it. Which page do you want to load? Because I don't provide any page in this repository. What it does is adding style to an element.

**Comment by duchao1990** [comment]
this is a list.html;  
 <ion-nav-view name="tab-something-list">
                  <ion-view view-title="something-list">
                    <ion-content>
                      <ion-list ng-controller="TalkCrtl">
                           content
                      </ion-list>
                    </ion-content>
                  </ion-view>
                </ion-nav-view>




<ion-slide><ion-nav-view name="list"></ion-nav-view></ion-slide>


I want load list.html

**Comment by duchao1990** [comment]
This is a list.html;  
                  <ion-view view-title="something-list">
                    <ion-content>
                      <ion-list ng-controller="TalkCrtl">
                           content
                      </ion-list>
                    </ion-content>
                  </ion-view>

<ion-slide><ion-nav-view name="list"></ion-nav-view></ion-slide>

I want load list.html 

------------------ 原始邮件 ------------------
发件人: "Wataru Oguchi";notifications@github.com;
发送时间: 2015年11月17日(星期二) 中午11:09
收件人: "wataruoguchi/Ionic-Tabbed-Slidebox-Scroll-Extension"Ionic-Tabbed-Slidebox-Scroll-Extension@noreply.github.com; 
抄送: "安心"384652412@qq.com; 
主题: Re: [Ionic-Tabbed-Slidebox-Scroll-Extension] Other pages (#1)

Hi @duchao1990 ,
 Sorry, I don't get it. Which page do you want to load? Because I don't provide any page in this repository. What it does is adding style to an element.

**Comment by wataruoguchi** [comment]
I don't think your question is relevant. If you want to add the page on your app, please look up official website.
