### ISSUE TITLE
dynamically adding content for each slide not working

### ISSUE THREAD

**Issue by mayurbaldha** [wataruoguchi/Ionic-Tabbed-Slidebox-Scroll-Extension#2]
Amazing Work ! I find difficulty when i use it dynamically adding content for each slide. e.g. let's say top tab bar have tabId & tabText (P.S. I am not talking about onSlideMove data.index of slidebox) is there any way that i can request tabId to get data for slide respectively.

**Comment by wataruoguchi** [comment]
Hi @mayurbaldha , thank you for the motivating message. I haven't though it yet but will take a look someday soon.

**Comment by wataruoguchi** [comment]
Hi @mayurbaldha
It seems that it better you to override the style of specific IDs to not be affected by this extension. This is just simply overriding style of `ion-content`.

**Comment by mayurbaldha** [comment]
@wataruoguchi Do you have any plunker for the thing you mentioned?

**Comment by wataruoguchi** [comment]
Unfortunately no, though please take a look at my code, it's not complicated. You can even folk it.
