### ISSUE TITLE
Disable horizontal bounce

### ISSUE THREAD

**Issue by anujsphinx** [wataruoguchi/Ionic-Tabbed-Slidebox-Scroll-Extension#3]
Great extension of the slider plugin but I am getting one problem for the horizontal bouncing .Will anyone help me to resolve this issue? My code is as following 

[issue.txt](https://github.com/wataruoguchi/Ionic-Tabbed-Slidebox-Scroll-Extension/files/162936/issue.txt)

**Comment by wataruoguchi** [comment]
Hi,

I won't work on it since I left Angular 1.x. Though in my opinion you should explain what the issue is, in detail, and tell what you've tried and failed, not only on this matter.
Then somebody who had the same problem would address the issue easily :)

Enjoy coding!

**Comment by anujsphinx** [comment]
Actually i want to disable bouncing effect here.when i am sliding it then screen is going up a little .

**Comment by anujsphinx** [comment]
![slide1](https://cloud.githubusercontent.com/assets/17042493/14698089/a3817488-07a8-11e6-893a-89adb5f33f82.PNG)
This is my first screen and when i am trying to slide screen then first screen is going up a little .
![issue2](https://cloud.githubusercontent.com/assets/17042493/14698105/cde71804-07a8-11e6-90b9-e16ffdb8c2e9.png)
